version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db

  db:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testtest
      MYSQL_DATABASE: ringfit-log
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
